config/routes.rb
Rails.application.routes.draw do
  resources :rooms

root 'rooms#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.order('name')
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.fetch(:room, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Appfolio Meeting Rooms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
<nav class="navbar navbar-dark bg-primary">
    <h1 class="navbar-brand">Appfolio Meeting Rooms</h1>
</nav>
<%= yield %>
</div>
</body>
</html>


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/t/bs-3.3.6/jq-2.2.0,dt-1.10.11,r-2.0.2/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/t/bs-3.3.6/jq-2.2.0,dt-1.10.11,r-2.0.2/datatables.min.js"></script>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_room_card.html.erb
      <% for room in @rooms do %>
      <div class="card">
        <div class="card-block">
          <h4 class="card-title"><%= room.name %></h4>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">City: <%= room.city %></li>
          <li class="list-group-item">Building: <%= room.building %></li>
          <li class="list-group-item">Floor: <%= room.floor %></li>
          <li class="list-group-item"># of People: <%= room.max_people %></li>
        </ul>
      </div>
      <% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class="container">
<div class='table-responsive'>
<table id="rooms" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th> Name </th>
      <th> Building </th>
      <th> Floor </th>
      <th> Location Notes </th>
      <th> Max People </th>
      <th> Outside Light </th>
      <th> Room Notes </th>
    </tr>
  </thead>
  <tbody>
    <% for room in @rooms do %>
    <tr>
      <td><%= room.name %></td>
      <td><%= room.building %></td>
      <td><%= room.floor %></td>
      <td><%= room.location_notes %></td>
      <td><%= room.max_people %></td>
      <td style="text-align:center"><% if room.windows %> <img src="http://www.free-icons-download.net/images/sun-icon-41809.png" class="img_fluid" style="max-width:30px; height:auto"><% else %>No <% end %> </td>
      <td><%= room.room_notes %></td>
    </tr>
    <% end %>
</table>
</div>
</div>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>